### ISSUE TITLE
User logged out unexpectedly / token expiry

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#1019]
This comment from #696, raised by Roxy and reported by others:

"Token expires after a few minutes sometimes (less than 10 minutes) and requires logging in again... but sometimes lasts for hours...?"

Unable to replicate, though would appear to still be a thing, hence raising an issue.

**Comment by CarlosNZ** [comment]
We still have the problem where it goes back to the login screen (but doesn't actually log out) after certain errors. Is that what this is, or something else?

**Comment by mark-prins** [comment]
Hopefully fixed with #1084 - will reopen if required

**Comment by DhanyaHerath** [comment]
We are still getting this on the V1.1.4 version - does seem random when we get logged out.

**Comment by CarlosNZ** [comment]
> We are still getting this on the V1.1.4 version - does seem random when we get logged out.

Are we seeing this on the live servers, or just running locally in dev mode?

**Comment by DhanyaHerath** [comment]
@CarlosNZ We were seeing it on the android tablets, installed as an apk

**Comment by jmbrunskill** [comment]
See my comment here:
https://github.com/openmsupply/health-supply-hub/pull/412#issuecomment-1459929812

Not sure if it's related but feels like a possiblity...
After this change I haven't seen the issue, with 2 minute refresh cookie interval.
As it's hard to replicate I'm not sure if I've really fixed it though of course.
Definitely fixes the problem where multiple refreshTokens are requested which seems like an improvement at least.

**Comment by mark-prins** [comment]
Thanks @jmbrunskill - though the change would cause the refresh token to be cached indefinitely, which would lead to issues. I'll check, hopefully there's another way to prevent the duplication?

**Comment by jmbrunskill** [comment]
@mark-prins we could go with @clemens-msupply suggestion and change to useMutation and create our own refreshInterval process rather than relying on the tanstack one? RefetchInterval isn't available with useMutation probably because normally people don't want to periodically run a mutation!

I wanted to minimise the changes too as changing this kind of code is risky :)
I'm pretty convinced what I've done will work fine, I don't think they are cached indefinitely, as the refetchInterval process effectively invalidated the cached value and re-runs the new query, but happy to be proven wrong!

Still not sure if I've really solved the unexpected logout either, it's very hard to figure out how to trigger it.

**Comment by mark-prins** [comment]
yeah! haven't found any reproducible scenario - and the issues raised are naturally pretty vague. I've not had an issue myself either, just relying on the 'I get logged out a lot' comments 🤷 

I'm refactoring the auth context atm, as that was doing far too much, and re-rendering which then caused further issues!

**Comment by clemens-msupply** [comment]
> @mark-prins we could go with @clemens-msupply suggestion and change to useMutation and create our own refreshInterval process rather than relying on the tanstack one? RefetchInterval isn't available with useMutation probably because normally people don't want to periodically run a mutation!

Oh yes sorry didn't fully realized that the useQuery timeout is used to renew the token :) Yes this should probably work then!

**Comment by mark-prins** [comment]
I've found a few things
- the refresh token process was not operating as expected; I've refactored the process
- the `AuthContext` is overloaded and was re-rendering more than I'd like. I've refactored and lifted out some hooks
- I have instances of the `syncInfo` request being sent without an authorization header; which then returns unauthorized and logs the user out. This is even though the auth cookie exists, with a valid token in it.
