### ISSUE TITLE
Adding new patients is not creating any sync records

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/open-msupply#1678]
## What went wrong? 😲
@clemens-msupply has setup a demo-oms site (v1.1.13) running with `oms/programs`. Adding new patients is not creating any sync records there 🤷

## Expected behaviour 🤔
Creating names should create sync records.

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Login into the demo-oms site (dispensary store) with `oms/programs` changes. (Details in BW?)
2. Create a new patient.
3. See error: no sync records has been created at all. Thus, you can't see the created patients  at mSupply Cloud either now!

## Your environment 🌱
 - Version: (v1.1.13)

**Comment by clemens-msupply** [comment]
It was a problem with Postgres migrations (regression from recent merge) 64bc7755. I will update the demo server and then it should be fixed.

**Comment by nisha-dangol** [comment]
> It was a problem with Postgres migrations (regression from recent merge) [64bc775](https://github.com/openmsupply/open-msupply/commit/64bc77557885f745a1d6b0287018891384543ccb). I will update the demo server and then it should be fixed.

Hey @clemens-msupply Have you updated the demo server yet? I tried creating some patients in [demo server](https://demo-open.msupply.org:88/). It's still not working for me!

**Comment by clemens-msupply** [comment]
Yes recreated the DB and it works for me. (When getting to the patient details page you still have to press the create button...)

**Comment by nisha-dangol** [comment]
> Yes recreated the DB and it works for me. (When getting to the patient details page you still have to press the create button...)

The demo-server finally looks updated. I see sync records being created and patient syncing to mSupply Cloud now.
