### ISSUE TITLE
Patient-code created in desktop are not handled well in oms

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/open-msupply#2045]
## What went wrong? 😲
Currently, oms expects the National ID (NID) to be in a certain format : 10 digit numbers only; which is mapped as patient_code in mSupply where there is no such restrictions on patient-code formats. Thus, the patients created in mSupply (in a different format, eg: alpha-numeric) are shown as inavlid in oms UI and won't let edit that patient details further! 

Maybe define why NID is in that format in the first place? Doesn't different clients/nations can have different formats for National ID's? Why limit to a certain format?

## Expected behaviour 🤔
The same patient-code in both mSupply and oms should be acceptable everywhere (be it desktop, mobile or oms)

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Have a sync setup with one remote desktop dispensary and one remote oms dispensary
2. Have the store pref `Patients created in other stores not visible in this store` ON for the ease of testing
3. Create a patient in desktop-store with patient code sth like `patient123` and sync
4. In remote-store, see that `patient123`.
5. Open that patient details
6. See error: NID is showing as invalid; and since it's a mandatory field, the Save button is disabled, thus preventing from adding/saving other details as well! 

## Screenshots
the patient created from mSupply Desktop and synced to oms-store:
<img width="1190" alt="image" src="https://github.com/openmsupply/open-msupply/assets/59193490/00f77823-aa6a-4d3f-aff5-04529113e241">
<img width="1246" alt="SCR-20230728-l82" src="https://github.com/openmsupply/open-msupply/assets/59193490/d357f0b9-3abd-4d9b-b369-0ee7ea37040c">

## Your environment 🌱

 - Version: v1.1.12 server exe, apk
 - Platform:
   - [x] android (tablet)
   - [x] browser (extra points if you tell us which one)
   - [x] server (windows)

**Comment by DhanyaHerath** [comment]
You're very right @nisha-dangol, that format restriction should only apply to PNG!

**Comment by clemens-msupply** [comment]
Could you please try again with the recent changes? Should be in 1.3.0. If programs isn't configured everything should work now...

**Comment by nisha-dangol** [comment]
> Could you please try again with the recent changes? Should be in 1.3.0. If programs isn't configured everything should work now...

Hi @clemens-msupply I have tried this in v1.3.00 exe as well. The issue still persists! 
What I did:
1. Created a patient from desktop remote store and synced
![image](https://github.com/openmsupply/open-msupply/assets/59193490/2ef337c6-4f6e-40d8-a48c-d008880a7862)
2. In oms, I see that patient
3. Still it shows NID as incorrect format:
<img width="1525" alt="image" src="https://github.com/openmsupply/open-msupply/assets/59193490/fb05642d-b673-43b6-9ca0-b923dfd1c961">
PS: I see the same behavior in both program-configured and one with no-program configs in oms!

**Comment by nisha-dangol** [comment]
> @nisha-dangol in the screenshot you still have programs configured. In this program configuration the `code` has to follow a specific format. 
>
In my current testing setup, there are multiple oms-sites; one site has program configs while the other DON'T. This was setup during running the FC code by adding users (for site to use programs).
This particular store/site do not have any programs as this user was not mentioned in FC code previously during program configs! 
<img width="1492" alt="image" src="https://github.com/openmsupply/open-msupply/assets/59193490/9521addd-a18c-4c83-ad06-f7e0739b3a4c">
<br><br>
>If you start with a clean datafile, e.g. HP, you will get a screen like:
>![image](https://github.com/openmsupply/open-msupply/assets/88299195/860bba0e-deed-4e55-89be-bb5b439f4f63)
>
>Same for the patient creation form. Without special config you will get a plain creation form:
>
I've not tried this in completely new datafile that doesn't use programs at all! MAybe I could try creating new site/store in same setup and check!

**Comment by roxy-dao** [comment]
Going to close this in favour of #2200 since the patient-code is technically solved on clean installs (without programs configured)

**Comment by nisha-dangol** [comment]
**Moving this to Done**, since patient codes (from mSupply desktop) looks fine in oms in clean/fresh datafile with no programs setup, except for #2200 
<br>
> In my current testing setup, there are multiple oms-sites; one site has program configs while the other DON'T. This was setup during running the FC code by adding users (for site to use programs). 
> 
As for this, this looks unlikely as NID will/should be used across a country, so i believe whole data(client) is either gonna use programs fully or not at all!
