### ISSUE TITLE
Cannot create Transgender female patient

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/open-msupply#2120]
## What went wrong? 😲
While creating new patient of `Transgender female` gender, it won't select the that gender at all. It only selects `Transgender male` option.

## Expected behaviour 🤔
Display the selected gender nicely as selected originally

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Create a new patient
2. While entering details, select gender as `Transgender female`
3. See error: it will select `Transgender Male` instead

## Screenshots/Recordings
https://recordit.co/8VcJxdMpFu

## Your environment 🌱

 - Version: v1.2.02 exe
 - Platform:
   - [ ] android (tablet)
   - [x] browser (extra points if you tell us which one)
   - [x] desktop (windows)
   - [ ] desktop (macOS)
   - [x] server (windows)

**Comment by roxy-dao** [comment]
It shows up as `Transgender Female` for me... Both the generic and programs patient creation should show it and you should be able to select it 🤔 

Can you reproduce @clemens-msupply ?

![Uploading Screenshot 2023-08-22 at 5.09.52 PM.png…]()

**Comment by clemens-msupply** [comment]
Thats weird, I also can select `Transgender Female` and it caries through to the creation view

**Comment by nisha-dangol** [comment]
@roxy-dao @clemens-msupply Tested this in mobile v1.2.02 apk as well. I also notice some weird behavior around the Gender field there; `Transgender Male` option is repeating twice in the list after entering some search values. See the video recording please:

https://github.com/openmsupply/open-msupply/assets/59193490/30fec47e-4ca8-4f53-8a4e-e5fc0240701e

**Comment by roxy-dao** [comment]
Closing since fixed in the program schema repo 

Will have to wait until next build to test though..

**Comment by nisha-dangol** [comment]
> Closing since fixed in the program schema repo (was caused by typo)
> 
> Will have to wait until next build to test though..

FYI, I was able to recreate this problem in latest build as well: v1.3.0-2158 built by @raviSussol on Jenkins just yesterday

**Comment by nisha-dangol** [comment]
> Closing since fixed in the program schema repo (was caused by typo)
> Will have to wait until next build to test though..

Hi @roxy-dao 
I checked this in v1.4.00-test exe as well. I still see the same behavior in my datafile (with programs config). Also, you can notice the same buggy behavior in [demo-oms](https://demo-open.msupply.org:88/) as well. 
But on checking this in another datafile (with no program configs), it was not replicable again. 
Any chances this could be because of those program configs?

**Comment by clemens-msupply** [comment]
I guess as well its because an (outdated?) program config. I just tried again on my local setup and it works fine.

We have to think about how we can automate our testing setup so that it becomes easy or at least easier to replicate a certain test setup including datafile, central and remote server...

**Comment by nisha-dangol** [comment]
Have retried and setup the new schema footrunner code on fresh datafile and the issue is not replicable anymore. So, will move this to **Done** since latest schemas doesn't show this problem
