### ISSUE TITLE
Sync fail between openMsupply and syncV5 desktop: No SI in omsupply store in the cloud

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/open-msupply#787]
## Issue Description
In a sync setup of cloud server running in syncV5 exe, with one remote server/omsupply (StoreA) and another remote syncV5 desktop site (StoreB) , it is seen that the stock transfer from StoreB (syncV5 desktop site) is not visible in StoreA (omsupply) 

Hi @Chris-Petty @alainsussol , you might wanna see this issue. I'm not exactly sure if this is issue in omsupply or syncV5 exe.

## Steps to Reproduce
1. Setup a sync system with cloud server running in syncV5 exe, with one remote server/omsupply (StoreA) and another remote syncV5 desktop site (StoreB).
2. Now, in syncV5 desktop site, login to StoreB and create a CI for StoreA and sync.
3. In omsupply, login to StoreA, sync and check for `Inbound Shipment`.
4. See errror: the SI is missing! 
5. Go to cloud server, login to StoreA and check for SI : it is missing there first! 

Interesting thing to note, stock transfer (`Outbound Shipment`) from StoreA to StoreB is working fine though!

**Comment by Chris-Petty** [comment]
@nisha-dangol Thanks for the find! We'll try reproduce. One note on your steps:

> Go to cloud server, login to StoreA and check for SI : it is missing there first!

This is a good check with mSupply desktop, but no longer the expected behaviour with open mSupply. In open mSupply the receiving site/store generates the SI (inbound shipment) on the receiving remote site, not the central server. So you would not expect to see the SI anywhere if the omsupply remote site did not generate it.

**Comment by Chris-Petty** [comment]
This is likely caused by #818

**Comment by Chris-Petty** [comment]
@nisha-dangol I think this should be fixed in the latest [`develop` build! ](https://www.dropbox.com/s/es51wsc7cfj19xx/omsupply-1-0-5-test1.zip?dl=1)

**Comment by nisha-dangol** [comment]
> @nisha-dangol I think this should be fixed in the latest [`develop` build! ](https://www.dropbox.com/s/es51wsc7cfj19xx/omsupply-1-0-5-test1.zip?dl=1)

@Chris-Petty 
Tested again with cloud in v7-00-beta40 and omsupply latest build v1.0.5-test1 (but it still shows as v1.04, another bug!)
The CI created from a remote desktop site (StoreB) still does not show up as a SI/Inbound Shipment in omsupply (StoreA).
But this seems to be working from remote desktop site v507 (syncV3 i suppose) to omsupply!

**Comment by Chris-Petty** [comment]
>  But this seems to be working from remote desktop site v507 (syncV3 i suppose) to omsupply!

@nisha-dangol to clarify the sync API versioning and mSupply application versioning:

- mSupply desktop _only_ syncs with Sync API V1
- Mobile syncs with API V3 (Some early early versions 5 years ago use sync API V2)
- OmSupply syncs with sync API V5 
- Sync API V5 is introduced in this latest release (mSupply desktop v700)

That is to say both mSupply v507 and v700 remote sites still sync with sync V1, but only v700 _central servers_ can _provide_ sync API v5. Weird that the remotes are behaving differently! Would you be able to share your omSupply database?

**Comment by nisha-dangol** [comment]
> > But this seems to be working from remote desktop site v507 (syncV3 i suppose) to omsupply!
> 
Would you be able to share your omSupply database?

[Here's](https://www.dropbox.com/s/0gbhu4er22vqiso/omsupply-database.zip?dl=0) the omsupply database.

**Comment by Chris-Petty** [comment]
@nisha-dangol @Pauline-mSupply @DamonRusden Tuning back in in 2023... this still an issue?

**Comment by Chris-Petty** [comment]
@nisha-dangol I just had a quick peek at the database. There are some integration errors for invoices on omSupply such as for invoice `6485` (was that the one you made? It has a comment "look at that one"): 

```
premature end of input at line 1 column 1194
```

These were some date time data conversion bugs that have [since been fixed](https://github.com/openmsupply/open-msupply/pull/885), so hopefully this is resolved! If not one is having issues from `Desktop` -> `Omsupply` then I think we can close this issue. Please bump/reopen otherwise!
